# Generated by Django 5.2 on 2025-05-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='preco',
            field=models.TextField(),
        ),
    ]
