# Generated by Django 5.2 on 2025-05-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_alter_veiculo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.PositiveSmallIntegerField(choices=[(1, 'AUDI'), (2, 'BMW'), (3, 'CHEVROLET - GM'), (4, 'FERRARI'), (5, 'FIAT'), (7, 'FORD'), (8, 'HONDA'), (9, 'HYUNDAI'), (10, 'VOLKSWAGEN'), (11, 'TOYOTA')]),
        ),
    ]
